[package]
name = "hgta1287dev/input-action-service"
description = "Simple InputActionService"
version = "1.0.0"
license = "MIT"
authors = ["hí <hoang1287dev@gmail.com>"]
realm = "shared"

[dependencies]